// GENERATED by scripts/bake-monogram.mjs from assets/monogram-lk.svg — do not edit.
// Regenerate: pnpm bake:monogram
export interface BakedShape {
  readonly points: readonly (readonly [number, number])[];
  readonly holes: readonly (readonly (readonly [number, number])[])[];
}

export const MONOGRAM_SHAPES: readonly BakedShape[] = [{"points":[[-1.0256,1],[-0.6667,1],[-0.6667,-0.641],[0,-0.641],[0,-1],[-1.0256,-1]],"holes":[]},{"points":[[-0.4103,0.0769],[0.5128,1],[1.0256,1],[0.1026,0.0769],[1.0256,-0.8462],[0.5128,-0.8462]],"holes":[]}];
