// GENERATED by scripts/bake-monogram.mjs from assets/monogram-lk.svg — do not edit.
// Regenerate: pnpm bake:monogram
export interface BakedShape {
  readonly points: readonly (readonly [number, number])[];
  readonly holes: readonly (readonly (readonly [number, number])[])[];
}

export const MONOGRAM_SHAPES: readonly BakedShape[] = [{"points":[[-1.2319,1],[-0.8551,1],[-0.8551,-0.6232],[0.1594,-0.6232],[0.1594,-1],[-1.2319,-1]],"holes":[]},{"points":[[-0.2464,1],[0.1304,1],[0.1304,-0.6232],[-0.2464,-0.6232]],"holes":[]},{"points":[[0.1304,0.1884],[0.913,1],[1.2319,1],[0.1304,-0.1304]],"holes":[]},{"points":[[0.1304,-0.1304],[0.7971,-1],[0.3913,-1],[0.1304,-0.4203]],"holes":[]}];
