// GENERATED by scripts/bake-monogram.mjs from assets/monogram-lk.svg — do not edit.
// Regenerate: pnpm bake:monogram
export interface BakedShape {
  readonly points: readonly (readonly [number, number])[];
  readonly holes: readonly (readonly (readonly [number, number])[])[];
}

export const MONOGRAM_SHAPES: readonly BakedShape[] = [{"points":[[-0.8276,0],[0,1],[0.8276,0],[0,-1]],"holes":[[[-0.7155,0],[0,-0.8655],[0.7155,0],[0,0.8655]]]},{"points":[[-0.3384,0.3429],[-0.2155,0.3429],[-0.2155,-0.2198],[0.0133,-0.2198],[0.0133,-0.3429],[-0.3384,-0.3429]],"holes":[]},{"points":[[-0.1538,0.0264],[0.1628,0.3429],[0.3386,0.3429],[0.0221,0.0264],[0.3386,-0.2902],[0.1628,-0.2902]],"holes":[]}];
